import { POKEMON_TYPE_ENUM } from '../enums';
import { PokemonDataType } from '../types';

const firstGenPokemonData : PokemonDataType[] = [
  {
    number: 1,
    name: "Bulbasaur",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 0.7,
    weight: 6.9,
    hp: 45,
    attack: 49,
    defense: 49,
    speed: 45
  },
  {
    number: 2,
    name: "Ivysaur",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 1,
    weight: 13,
    hp: 60,
    attack: 62,
    defense: 63,
    speed: 60
  },
  {
    number: 3,
    name: "Venusaur",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 2,
    weight: 100,
    hp: 80,
    attack: 82,
    defense: 83,
    speed: 80
  },
  {
    number: 4,
    name: "Charmander",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 0.6,
    weight: 8.5,
    hp: 39,
    attack: 52,
    defense: 43,
    speed: 65
  },
  {
    number: 5,
    name: "Charmeleon",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 1.1,
    weight: 19,
    hp: 58,
    attack: 64,
    defense: 58,
    speed: 80
  },
  {
    number: 6,
    name: "Charizard",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 1.7,
    weight: 90.5,
    hp: 78,
    attack: 84,
    defense: 78,
    speed: 100
  },
  {
    number: 7,
    name: "Squirtle",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.5,
    weight: 9,
    hp: 44,
    attack: 48,
    defense: 65,
    speed: 43
  },
  {
    number: 8,
    name: "Wartortle",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1,
    weight: 22.5,
    hp: 59,
    attack: 63,
    defense: 80,
    speed: 58
  },
  {
    number: 9,
    name: "Blastoise",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.6,
    weight: 85.5,
    hp: 79,
    attack: 83,
    defense: 100,
    speed: 78
  },
  {
    number: 10,
    name: "Caterpie",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 0.3,
    weight: 2.9,
    hp: 45,
    attack: 30,
    defense: 35,
    speed: 45
  },
  {
    number: 11,
    name: "Metapod",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 0.7,
    weight: 9.9,
    hp: 50,
    attack: 20,
    defense: 55,
    speed: 30
  },
  {
    number: 12,
    name: "Butterfree",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 1.1,
    weight: 32,
    hp: 60,
    attack: 45,
    defense: 50,
    speed: 70
  },
  {
    number: 13,
    name: "Weedle",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 0.3,
    weight: 3.2,
    hp: 40,
    attack: 35,
    defense: 30,
    speed: 50
  },
  {
    number: 14,
    name: "Kakuna",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 0.6,
    weight: 10,
    hp: 45,
    attack: 25,
    defense: 50,
    speed: 35
  },
  {
    number: 15,
    name: "Beedrill",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 1,
    weight: 29.5,
    hp: 65,
    attack: 80,
    defense: 40,
    speed: 75
  },
  {
    number: 16,
    name: "Pidgey",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.3,
    weight: 1.8,
    hp: 40,
    attack: 45,
    defense: 40,
    speed: 56
  },
  {
    number: 17,
    name: "Pidgeotto",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.1,
    weight: 30,
    hp: 63,
    attack: 60,
    defense: 55,
    speed: 71
  },
  {
    number: 18,
    name: "Pidgeot",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.5,
    weight: 39.5,
    hp: 83,
    attack: 80,
    defense: 75,
    speed: 91
  },
  {
    number: 19,
    name: "Rattata",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.3,
    weight: 3.5,
    hp: 30,
    attack: 56,
    defense: 35,
    speed: 72
  },
  {
    number: 20,
    name: "Raticate",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.7,
    weight: 18.5,
    hp: 55,
    attack: 81,
    defense: 60,
    speed: 97
  },
  {
    number: 21,
    name: "Spearow",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.3,
    weight: 2,
    hp: 40,
    attack: 60,
    defense: 30,
    speed: 70
  },
  {
    number: 22,
    name: "Fearow",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.2,
    weight: 38,
    hp: 65,
    attack: 90,
    defense: 65,
    speed: 100
  },
  {
    number: 23,
    name: "Ekans",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 2,
    weight: 6.9,
    hp: 35,
    attack: 60,
    defense: 44,
    speed: 55
  },
  {
    number: 24,
    name: "Arbok",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 3.5,
    weight: 65,
    hp: 60,
    attack: 85,
    defense: 69,
    speed: 80
  },
  {
    number: 25,
    name: "Pikachu",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 0.4,
    weight: 6,
    hp: 35,
    attack: 55,
    defense: 30,
    speed: 90
  },
  {
    number: 26,
    name: "Raichu",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 0.8,
    weight: 30,
    hp: 60,
    attack: 90,
    defense: 55,
    speed: 100
  },
  {
    number: 27,
    name: "Sandshrew",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 0.6,
    weight: 12,
    hp: 50,
    attack: 75,
    defense: 85,
    speed: 40
  },
  {
    number: 28,
    name: "Sandslash",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 1,
    weight: 29.5,
    hp: 75,
    attack: 100,
    defense: 110,
    speed: 65
  },
  {
    number: 29,
    name: "Nidoran",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 0.4,
    weight: 7,
    hp: 55,
    attack: 47,
    defense: 52,
    speed: 41
  },
  {
    number: 30,
    name: "Nidorina",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 0.8,
    weight: 20,
    hp: 70,
    attack: 62,
    defense: 67,
    speed: 56
  },
  {
    number: 31,
    name: "Nidoqueen",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 1.3,
    weight: 60,
    hp: 90,
    attack: 82,
    defense: 87,
    speed: 76
  },
  {
    number: 32,
    name: "Nidoran",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 0.5,
    weight: 9,
    hp: 46,
    attack: 57,
    defense: 40,
    speed: 50
  },
  {
    number: 33,
    name: "Nidorino",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 0.9,
    weight: 19.5,
    hp: 61,
    attack: 72,
    defense: 57,
    speed: 65
  },
  {
    number: 34,
    name: "Nidoking",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 1.4,
    weight: 62,
    hp: 81,
    attack: 92,
    defense: 77,
    speed: 85
  },
  {
    number: 35,
    name: "Clefairy",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.6,
    weight: 7.5,
    hp: 70,
    attack: 45,
    defense: 48,
    speed: 35
  },
  {
    number: 36,
    name: "Clefable",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.3,
    weight: 40,
    hp: 95,
    attack: 70,
    defense: 73,
    speed: 60
  },
  {
    number: 37,
    name: "Vulpix",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 0.6,
    weight: 9.9,
    hp: 38,
    attack: 41,
    defense: 40,
    speed: 65
  },
  {
    number: 38,
    name: "Ninetales",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 1.1,
    weight: 19.9,
    hp: 73,
    attack: 76,
    defense: 75,
    speed: 100
  },
  {
    number: 39,
    name: "Jigglypuff",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.5,
    weight: 5.5,
    hp: 115,
    attack: 45,
    defense: 20,
    speed: 20
  },
  {
    number: 40,
    name: "Wigglytuff",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1,
    weight: 12,
    hp: 140,
    attack: 70,
    defense: 45,
    speed: 45
  },
  {
    number: 41,
    name: "Zubat",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 0.8,
    weight: 7.5,
    hp: 40,
    attack: 45,
    defense: 35,
    speed: 55
  },
  {
    number: 42,
    name: "Golbat",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 1.6,
    weight: 55,
    hp: 75,
    attack: 80,
    defense: 70,
    speed: 90
  },
  {
    number: 43,
    name: "Oddish",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 0.5,
    weight: 5.4,
    hp: 45,
    attack: 50,
    defense: 55,
    speed: 30
  },
  {
    number: 44,
    name: "Gloom",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 0.8,
    weight: 8.6,
    hp: 60,
    attack: 65,
    defense: 70,
    speed: 40
  },
  {
    number: 45,
    name: "Vileplume",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 1.2,
    weight: 18.6,
    hp: 75,
    attack: 80,
    defense: 85,
    speed: 50
  },
  {
    number: 46,
    name: "Paras",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 0.3,
    weight: 5.4,
    hp: 35,
    attack: 70,
    defense: 55,
    speed: 25
  },
  {
    number: 47,
    name: "Parasect",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 1,
    weight: 29.5,
    hp: 60,
    attack: 95,
    defense: 80,
    speed: 30
  },
  {
    number: 48,
    name: "Venonat",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 1,
    weight: 30,
    hp: 60,
    attack: 55,
    defense: 50,
    speed: 45
  },
  {
    number: 49,
    name: "Venomoth",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 1.5,
    weight: 12.5,
    hp: 70,
    attack: 65,
    defense: 60,
    speed: 90
  },
  {
    number: 50,
    name: "Diglett",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 0.2,
    weight: 0.8,
    hp: 10,
    attack: 55,
    defense: 25,
    speed: 95
  },
  {
    number: 51,
    name: "Dugtrio",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 0.7,
    weight: 33.3,
    hp: 35,
    attack: 80,
    defense: 50,
    speed: 120
  },
  {
    number: 52,
    name: "Meowth",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.4,
    weight: 4.2,
    hp: 40,
    attack: 45,
    defense: 35,
    speed: 90
  },
  {
    number: 53,
    name: "Persian",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1,
    weight: 32,
    hp: 65,
    attack: 70,
    defense: 60,
    speed: 115
  },
  {
    number: 54,
    name: "Psyduck",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.8,
    weight: 19.6,
    hp: 50,
    attack: 52,
    defense: 48,
    speed: 55
  },
  {
    number: 55,
    name: "Golduck",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.7,
    weight: 76.6,
    hp: 80,
    attack: 82,
    defense: 78,
    speed: 85
  },
  {
    number: 56,
    name: "Mankey",
    type: POKEMON_TYPE_ENUM.FIGHTING,
    height: 0.5,
    weight: 28,
    hp: 40,
    attack: 80,
    defense: 35,
    speed: 70
  },
  {
    number: 57,
    name: "Primeape",
    type: POKEMON_TYPE_ENUM.FIGHTING,
    height: 1,
    weight: 32,
    hp: 65,
    attack: 105,
    defense: 60,
    speed: 95
  },
  {
    number: 58,
    name: "Growlithe",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 0.7,
    weight: 19,
    hp: 55,
    attack: 70,
    defense: 45,
    speed: 60
  },
  {
    number: 59,
    name: "Arcanine",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 1.9,
    weight: 155,
    hp: 90,
    attack: 110,
    defense: 80,
    speed: 95
  },
  {
    number: 60,
    name: "Poliwag",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.6,
    weight: 12.4,
    hp: 40,
    attack: 50,
    defense: 40,
    speed: 90
  },
  {
    number: 61,
    name: "Poliwhirl",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1,
    weight: 20,
    hp: 65,
    attack: 65,
    defense: 65,
    speed: 90
  },
  {
    number: 62,
    name: "Poliwrath",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.3,
    weight: 54,
    hp: 90,
    attack: 85,
    defense: 95,
    speed: 70
  },
  {
    number: 63,
    name: "Abra",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 0.9,
    weight: 19.5,
    hp: 25,
    attack: 20,
    defense: 15,
    speed: 90
  },
  {
    number: 64,
    name: "Kadabra",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 1.3,
    weight: 56.5,
    hp: 40,
    attack: 35,
    defense: 30,
    speed: 105
  },
  {
    number: 65,
    name: "Alakazam",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 1.5,
    weight: 48,
    hp: 55,
    attack: 50,
    defense: 45,
    speed: 120
  },
  {
    number: 66,
    name: "Machop",
    type: POKEMON_TYPE_ENUM.FIGHTING,
    height: 0.8,
    weight: 19.5,
    hp: 70,
    attack: 80,
    defense: 50,
    speed: 35
  },
  {
    number: 67,
    name: "Machoke",
    type: POKEMON_TYPE_ENUM.FIGHTING,
    height: 1.5,
    weight: 70.5,
    hp: 80,
    attack: 100,
    defense: 70,
    speed: 45
  },
  {
    number: 68,
    name: "Machamp",
    type: POKEMON_TYPE_ENUM.FIGHTING,
    height: 1.6,
    weight: 130,
    hp: 90,
    attack: 130,
    defense: 80,
    speed: 55
  },
  {
    number: 69,
    name: "Bellsprout",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 0.7,
    weight: 4,
    hp: 50,
    attack: 75,
    defense: 35,
    speed: 40
  },
  {
    number: 70,
    name: "Weepinbell",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 1,
    weight: 6.4,
    hp: 65,
    attack: 90,
    defense: 50,
    speed: 55
  },
  {
    number: 71,
    name: "Victreebel",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 1.7,
    weight: 15.5,
    hp: 80,
    attack: 105,
    defense: 65,
    speed: 70
  },
  {
    number: 72,
    name: "Tentacool",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.9,
    weight: 45.5,
    hp: 40,
    attack: 40,
    defense: 35,
    speed: 70
  },
  {
    number: 73,
    name: "Tentacruel",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.6,
    weight: 55,
    hp: 80,
    attack: 70,
    defense: 65,
    speed: 100
  },
  {
    number: 74,
    name: "Geodude",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 0.4,
    weight: 20,
    hp: 40,
    attack: 80,
    defense: 100,
    speed: 20
  },
  {
    number: 75,
    name: "Graveler",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 1,
    weight: 105,
    hp: 55,
    attack: 95,
    defense: 115,
    speed: 35
  },
  {
    number: 76,
    name: "Golem",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 1.4,
    weight: 300,
    hp: 80,
    attack: 110,
    defense: 130,
    speed: 45
  },
  {
    number: 77,
    name: "Ponyta",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 1,
    weight: 30,
    hp: 50,
    attack: 85,
    defense: 55,
    speed: 90
  },
  {
    number: 78,
    name: "Rapidash",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 1.7,
    weight: 95,
    hp: 65,
    attack: 100,
    defense: 70,
    speed: 105
  },
  {
    number: 79,
    name: "Slowpoke",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.2,
    weight: 36,
    hp: 90,
    attack: 65,
    defense: 65,
    speed: 15
  },
  {
    number: 80,
    name: "Slowbro",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.6,
    weight: 78.5,
    hp: 95,
    attack: 75,
    defense: 110,
    speed: 30
  },
  {
    number: 81,
    name: "Magnemite",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 0.3,
    weight: 6,
    hp: 25,
    attack: 35,
    defense: 70,
    speed: 45
  },
  {
    number: 82,
    name: "Magneton",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 1,
    weight: 60,
    hp: 50,
    attack: 60,
    defense: 95,
    speed: 70
  },
  {
    number: 83,
    name: "Farfetchd",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.8,
    weight: 15,
    hp: 52,
    attack: 65,
    defense: 55,
    speed: 60
  },
  {
    number: 84,
    name: "Doduo",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.4,
    weight: 39.2,
    hp: 35,
    attack: 85,
    defense: 45,
    speed: 75
  },
  {
    number: 85,
    name: "Dodrio",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.8,
    weight: 85.2,
    hp: 60,
    attack: 110,
    defense: 70,
    speed: 100
  },
  {
    number: 86,
    name: "Seel",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.1,
    weight: 90,
    hp: 65,
    attack: 45,
    defense: 55,
    speed: 45
  },
  {
    number: 87,
    name: "Dewgong",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.7,
    weight: 120,
    hp: 90,
    attack: 70,
    defense: 80,
    speed: 70
  },
  {
    number: 88,
    name: "Grimer",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 0.9,
    weight: 30,
    hp: 80,
    attack: 80,
    defense: 50,
    speed: 25
  },
  {
    number: 89,
    name: "Muk",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 1.2,
    weight: 30,
    hp: 105,
    attack: 105,
    defense: 75,
    speed: 50
  },
  {
    number: 90,
    name: "Shellder",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.3,
    weight: 4,
    hp: 30,
    attack: 65,
    defense: 100,
    speed: 40
  },
  {
    number: 91,
    name: "Cloyster",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.5,
    weight: 132.5,
    hp: 50,
    attack: 95,
    defense: 180,
    speed: 70
  },
  {
    number: 92,
    name: "Gastly",
    type: POKEMON_TYPE_ENUM.GHOST,
    height: 1.3,
    weight: 0.1,
    hp: 30,
    attack: 35,
    defense: 30,
    speed: 80
  },
  {
    number: 93,
    name: "Haunter",
    type: POKEMON_TYPE_ENUM.GHOST,
    height: 1.6,
    weight: 0.1,
    hp: 45,
    attack: 50,
    defense: 45,
    speed: 95
  },
  {
    number: 94,
    name: "Gengar",
    type: POKEMON_TYPE_ENUM.GHOST,
    height: 1.5,
    weight: 40.5,
    hp: 60,
    attack: 65,
    defense: 60,
    speed: 110
  },
  {
    number: 95,
    name: "Onix",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 8.8,
    weight: 210,
    hp: 35,
    attack: 45,
    defense: 160,
    speed: 70
  },
  {
    number: 96,
    name: "Drowzee",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 1,
    weight: 32.4,
    hp: 60,
    attack: 48,
    defense: 45,
    speed: 42
  },
  {
    number: 97,
    name: "Hypno",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 1.6,
    weight: 75.6,
    hp: 85,
    attack: 73,
    defense: 70,
    speed: 67
  },
  {
    number: 98,
    name: "Krabby",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.4,
    weight: 6.5,
    hp: 30,
    attack: 105,
    defense: 90,
    speed: 50
  },
  {
    number: 99,
    name: "Kingler",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.3,
    weight: 60,
    hp: 55,
    attack: 130,
    defense: 115,
    speed: 75
  },
  {
    number: 100,
    name: "Voltorb",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 0.5,
    weight: 10.4,
    hp: 40,
    attack: 30,
    defense: 50,
    speed: 100
  },
  {
    number: 101,
    name: "Electrode",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 1.2,
    weight: 66.6,
    hp: 60,
    attack: 50,
    defense: 70,
    speed: 140
  },
  {
    number: 102,
    name: "Exeggcute",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 0.4,
    weight: 2.5,
    hp: 60,
    attack: 40,
    defense: 80,
    speed: 40
  },
  {
    number: 103,
    name: "Exeggutor",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 2,
    weight: 120,
    hp: 95,
    attack: 95,
    defense: 85,
    speed: 55
  },
  {
    number: 104,
    name: "Cubone",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 0.4,
    weight: 6.5,
    hp: 50,
    attack: 50,
    defense: 95,
    speed: 35
  },
  {
    number: 105,
    name: "Marowak",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 1,
    weight: 45,
    hp: 60,
    attack: 80,
    defense: 110,
    speed: 45
  },
  {
    number: 106,
    name: "Hitmonlee",
    type: POKEMON_TYPE_ENUM.FIGHTING,
    height: 1.5,
    weight: 49.8,
    hp: 50,
    attack: 120,
    defense: 53,
    speed: 87
  },
  {
    number: 107,
    name: "Hitmonchan",
    type: POKEMON_TYPE_ENUM.FIGHTING,
    height: 1.4,
    weight: 50.2,
    hp: 50,
    attack: 105,
    defense: 79,
    speed: 76
  },
  {
    number: 108,
    name: "Lickitung",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.2,
    weight: 65.5,
    hp: 90,
    attack: 55,
    defense: 75,
    speed: 30
  },
  {
    number: 109,
    name: "Koffing",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 0.6,
    weight: 1,
    hp: 40,
    attack: 65,
    defense: 95,
    speed: 35
  },
  {
    number: 110,
    name: "Weezing",
    type: POKEMON_TYPE_ENUM.POISON,
    height: 1.2,
    weight: 9.5,
    hp: 65,
    attack: 90,
    defense: 120,
    speed: 60
  },
  {
    number: 111,
    name: "Rhyhorn",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 1,
    weight: 115,
    hp: 80,
    attack: 85,
    defense: 95,
    speed: 25
  },
  {
    number: 112,
    name: "Rhydon",
    type: POKEMON_TYPE_ENUM.GROUND,
    height: 1.9,
    weight: 120,
    hp: 105,
    attack: 130,
    defense: 120,
    speed: 40
  },
  {
    number: 113,
    name: "Chansey",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.1,
    weight: 34.6,
    hp: 250,
    attack: 5,
    defense: 5,
    speed: 50
  },
  {
    number: 114,
    name: "Tangela",
    type: POKEMON_TYPE_ENUM.GRASS,
    height: 1,
    weight: 35,
    hp: 65,
    attack: 55,
    defense: 115,
    speed: 60
  },
  {
    number: 115,
    name: "Kangaskhan",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 2.2,
    weight: 80,
    hp: 105,
    attack: 95,
    defense: 80,
    speed: 90
  },
  {
    number: 116,
    name: "Horsea",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.4,
    weight: 8,
    hp: 30,
    attack: 40,
    defense: 70,
    speed: 60
  },
  {
    number: 117,
    name: "Seadra",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.2,
    weight: 25,
    hp: 55,
    attack: 65,
    defense: 95,
    speed: 85
  },
  {
    number: 118,
    name: "Goldeen",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.6,
    weight: 15,
    hp: 45,
    attack: 67,
    defense: 60,
    speed: 63
  },
  {
    number: 119,
    name: "Seaking",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.3,
    weight: 39,
    hp: 80,
    attack: 92,
    defense: 65,
    speed: 68
  },
  {
    number: 120,
    name: "Staryu",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.8,
    weight: 34.5,
    hp: 30,
    attack: 45,
    defense: 55,
    speed: 85
  },
  {
    number: 121,
    name: "Starmie",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1.1,
    weight: 80,
    hp: 60,
    attack: 75,
    defense: 85,
    speed: 115
  },
  {
    number: 122,
    name: "MrMime",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 1.3,
    weight: 54.5,
    hp: 40,
    attack: 45,
    defense: 65,
    speed: 90
  },
  {
    number: 123,
    name: "Scyther",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 1.5,
    weight: 56,
    hp: 70,
    attack: 110,
    defense: 80,
    speed: 105
  },
  {
    number: 124,
    name: "Jynx",
    type: POKEMON_TYPE_ENUM.ICE,
    height: 1.4,
    weight: 40.6,
    hp: 65,
    attack: 50,
    defense: 35,
    speed: 95
  },
  {
    number: 125,
    name: "Electabuzz",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 1.1,
    weight: 30,
    hp: 65,
    attack: 83,
    defense: 57,
    speed: 105
  },
  {
    number: 126,
    name: "Magmar",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 1.3,
    weight: 44.5,
    hp: 65,
    attack: 95,
    defense: 57,
    speed: 93
  },
  {
    number: 127,
    name: "Pinsir",
    type: POKEMON_TYPE_ENUM.BUG,
    height: 1.5,
    weight: 55,
    hp: 65,
    attack: 125,
    defense: 100,
    speed: 85
  },
  {
    number: 128,
    name: "Tauros",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 1.4,
    weight: 88.4,
    hp: 75,
    attack: 100,
    defense: 95,
    speed: 110
  },
  {
    number: 129,
    name: "Magikarp",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 0.9,
    weight: 10,
    hp: 20,
    attack: 10,
    defense: 55,
    speed: 80
  },
  {
    number: 130,
    name: "Gyarados",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 6.5,
    weight: 235,
    hp: 95,
    attack: 125,
    defense: 79,
    speed: 81
  },
  {
    number: 131,
    name: "Lapras",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 2.5,
    weight: 220,
    hp: 130,
    attack: 85,
    defense: 80,
    speed: 60
  },
  {
    number: 132,
    name: "Ditto",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.3,
    weight: 4,
    hp: 48,
    attack: 48,
    defense: 48,
    speed: 48
  },
  {
    number: 133,
    name: "Eevee",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.3,
    weight: 6.5,
    hp: 55,
    attack: 55,
    defense: 50,
    speed: 55
  },
  {
    number: 134,
    name: "Vaporeon",
    type: POKEMON_TYPE_ENUM.WATER,
    height: 1,
    weight: 29,
    hp: 130,
    attack: 65,
    defense: 60,
    speed: 65
  },
  {
    number: 135,
    name: "Jolteon",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 0.8,
    weight: 24.5,
    hp: 65,
    attack: 65,
    defense: 60,
    speed: 130
  },
  {
    number: 136,
    name: "Flareon",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 0.9,
    weight: 25,
    hp: 65,
    attack: 130,
    defense: 60,
    speed: 65
  },
  {
    number: 137,
    name: "Porygon",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 0.8,
    weight: 36.5,
    hp: 65,
    attack: 60,
    defense: 70,
    speed: 40
  },
  {
    number: 138,
    name: "Omanyte",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 0.4,
    weight: 7.5,
    hp: 35,
    attack: 40,
    defense: 100,
    speed: 35
  },
  {
    number: 139,
    name: "Omastar",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 1,
    weight: 35,
    hp: 70,
    attack: 60,
    defense: 125,
    speed: 55
  },
  {
    number: 140,
    name: "Kabuto",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 0.5,
    weight: 11.5,
    hp: 30,
    attack: 80,
    defense: 90,
    speed: 55
  },
  {
    number: 141,
    name: "Kabutops",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 1.3,
    weight: 40.5,
    hp: 60,
    attack: 115,
    defense: 105,
    speed: 80
  },
  {
    number: 142,
    name: "Aerodactyl",
    type: POKEMON_TYPE_ENUM.ROCK,
    height: 1.8,
    weight: 59,
    hp: 80,
    attack: 105,
    defense: 65,
    speed: 130
  },
  {
    number: 143,
    name: "Snorlax",
    type: POKEMON_TYPE_ENUM.NORMAL,
    height: 2.1,
    weight: 460,
    hp: 160,
    attack: 110,
    defense: 65,
    speed: 30
  },
  {
    number: 144,
    name: "Articuno",
    type: POKEMON_TYPE_ENUM.ICE,
    height: 1.7,
    weight: 55.4,
    hp: 90,
    attack: 85,
    defense: 100,
    speed: 85
  },
  {
    number: 145,
    name: "Zapdos",
    type: POKEMON_TYPE_ENUM.ELECTRIC,
    height: 1.6,
    weight: 52.6,
    hp: 90,
    attack: 90,
    defense: 85,
    speed: 100
  },
  {
    number: 146,
    name: "Moltres",
    type: POKEMON_TYPE_ENUM.FIRE,
    height: 2,
    weight: 60,
    hp: 90,
    attack: 100,
    defense: 90,
    speed: 90
  },
  {
    number: 147,
    name: "Dratini",
    type: POKEMON_TYPE_ENUM.DRAGON,
    height: 1.8,
    weight: 3.3,
    hp: 41,
    attack: 64,
    defense: 45,
    speed: 50
  },
  {
    number: 148,
    name: "Dragonair",
    type: POKEMON_TYPE_ENUM.DRAGON,
    height: 4,
    weight: 16.5,
    hp: 61,
    attack: 84,
    defense: 65,
    speed: 70
  },
  {
    number: 149,
    name: "Dragonite",
    type: POKEMON_TYPE_ENUM.DRAGON,
    height: 2.2,
    weight: 210,
    hp: 91,
    attack: 134,
    defense: 95,
    speed: 80
  },
  {
    number: 150,
    name: "Mewtwo",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 2,
    weight: 122,
    hp: 106,
    attack: 110,
    defense: 90,
    speed: 130
  },
  {
    number: 151,
    name: "Mew",
    type: POKEMON_TYPE_ENUM.PSYCHIC,
    height: 0.4,
    weight: 4,
    hp: 100,
    attack: 100,
    defense: 100,
    speed: 100
  }
];

export default firstGenPokemonData;